name: Build & Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
      - run: make dep
      - run: make build
      - run: make test
